// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rianhbfzseeccjjmoroj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpYW5oYmZ6c2VlY2Nqam1vcm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjU1NjYsImV4cCI6MjA2NTUwMTU2Nn0.23g81_RN_srSdgHTQEjm63rKWdpnrU0-mRaGdITFK1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);